# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - expenseapi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.400' # Adjust for your .NET version

      - name: Restore NuGet packages
        run: dotnet restore ExpenseHound.API/ExpenseHound.API.csproj

      - name: Build the project
        run: dotnet build --configuration Release ExpenseHound.API/ExpenseHound.API.csproj

      - name: Publish to folder
        run: dotnet publish --configuration Release --output ./published ExpenseHound.API/ExpenseHound.API.csproj

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: ./published/**

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app

      - name: Set up Azure CLI
        uses: azure/setup-azurecli@v1

      - name: Azure Login via CLI
        run: |
          az login --service-principal --username ${{ secrets.AZUREAPPSERVICE_CLIENTID }} --password ${{ secrets.AZUREAPPSERVICE_CLIENTSECRET }} --tenant ${{ secrets.AZUREAPPSERVICE_TENANTID }}

      - name: Deploy to Azure Web App using Azure CLI
        run: |
          az webapp deploy --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --src-path ./published --type zip
